<?php
/**
 * @var $block \Ebizmarts\MailChimp\Block\Adminhtml\Customer\Edit\Tabs\View\Customer
 * @var $escaper \Magento\Framework\Escaper
 */
$interest = $block->getInterest();
?>
<div class="fieldset-wrapper">
    <div class="fieldset-wrapper-title">
        <span class="title"><?= $escaper->escapeHtml(__('MailChimp Information')) ?></span>
    </div>
    <div class="admin__fieldset-wrapper-content">
    <fieldset class="admin__fieldset">
    <?php if (count($interest)): ?>
        <?php foreach ($interest as $i): ?>
            <div class="admin__field">
                <label class="admin__field-label" for="<?= $escaper->escapeHtml($i['interest']['id']) ?>">
                    <span><?= $escaper->escapeHtml($i['interest']['title']) ?></span>
                </label>
                <div class="admin__field-control control">
                    <div class="fields">
                        <?php switch ($i['interest']['type']):
                            case 'checkboxes': ?>
                                <ul class="admin_field_field field" style="list-style: none">
                                    <?php foreach ($i['category'] as $c): ?>
                                        <li class="field no-label">
                                            <input
                                                   name="customer[interestgroup]\
                                                   [<?= $escaper->escapeHtml($i['interest']['id']) ?>]\
                                                   [<?= $escaper->escapeHtml($c['id']) ?>]"
                                                   type="checkbox"
                                                   data-form-part="customer_form"
                                                   value="<?= $escaper->escapeHtml($c['id']) ?>"
                                                   id="<?= $escaper->escapeHtml('mailchimp_group_'.$c['id']) ?>"
                                                   title="<?= $escaper->escapeHtml($c['name']) ?>"
                                                <?php if ($c['checked']) { echo $escaper->escapeHtml('checked');} ?>
                                            />
                                            <label class="field label"><?= $escaper->escapeHtml($c['name']) ?></label>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                                <?php       break;
                            case 'dropdown': ?>
                                <div class="field no-label">
                                    <select class="admin_field_field field"
                                            data-form-part="customer_form"
                                            name="customer[interestgroup]\
                                            [<?= $escaper->escapeHtml($i['interest']['id']) ?>]"
                                            id="<?= $escaper->escapeHtml('mailchimp_group_'.$i['interest']['id']) ?>"
                                            title="<?= $escaper->escapeHtml($i['interest']['title']) ?>">
                                        <option value=""></option>
                                        <?php foreach ($i['category'] as $c): ?>
                                            <option value="<?= $escaper->escapeHtml($c['id']) ?>" \
                                                <?php if ($c['checked']) {
                                                    echo $escaper->escapeHtml('selected');
                                                } ?>><?= $escaper->escapeHtml($c['name']) ?></option>
                                        <?php endforeach; ?>
                                    </select>

                                </div>
                                <?php       break;
                            case 'radio': ?>
                                <ul class="admin_field_field field">
                                    <?php foreach ($i['category'] as $c): ?>
                                        <li class="field no-label" style="list-style: none">
                                            <input class=""
                                                   name="customer[interestgroup]\
                                                   [<?= $escaper->escapeHtml($i['interest']['id']) ?>]"
                                                   type="radio"
                                                   data-form-part="customer_form"
                                                   value="<?= $escaper->escapeHtml($c['id']) ?>"
                                                   id="<?= $escaper->escapeHtml('mailchimp_group_'.$c['id']) ?>"
                                                   title="<?= $escaper->escapeHtml($c['name']) ?>"
                                                <?php if ($c['checked']) { echo $escaper->escapeHtml('checked');} ?>
                                            />
                                            <label class="field label"><?= $escaper->escapeHtml($c['name']) ?></label>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                                <?php       break; ?>
                            <?php endswitch; ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <div class="admin__field">
        <?= $escaper->escapeHtml(__("No Interest groups found")); ?>
        </div>
    <?php endif; ?>
</fieldset>
    </div>
</div>
