<?php
/**
 * @var $block \Ebizmarts\MailChimp\Block\checkout\Success
 */
$interest = $block->getInterest();
//echo $interest;
?>
<p>
    <?php echo $block->escapeHtml($block->getMessageBefore()) ?>
<form class="form" action="<?php echo $block->escapeHtml($block->getFormUrl()) ?>" method="get" id="mailchimp-groups">
    <fieldset class="fieldset">
            <?php foreach($interest as $i): ?>
                <div class="field">
                    <label class="label" for="<?php echo $block->escapeHtml($i['interest']['id']) ?>">
                        <span><?php echo $block->escapeHtml($i['interest']['title']) ?></span>
                    </label>
                    <div class="control">
                        <div class="fields">
                            <?php switch($i['interest']['type']):
                                case 'checkboxes': ?>
                                    <ul class="field" style="list-style: none">
                                    <?php foreach($i['category'] as $c): ?>
                                        <li class="field no-label">
                                            <input class=""
                                                   name="group[<?php echo $block->escapeHtml($i['interest']['id']) ?>][<?php echo $block->escapeHtml($c['id'])?>]"
                                                   type="checkbox"
                                                   value="<?php echo $block->escapeHtml($c['id']) ?>"
                                                   id="<?php echo 'mailchimp_group_'.$block->escapeHtml($c['id']) ?>"
                                                   title="<?php echo $block->escapeHtml($c['name']) ?>"
                                                   <?php if($c['checked']) { echo 'checked';} ?>
                                            />
                                            <label class="field label"><?php echo $block->escapeHtml($c['name'])?></label>
                                        </li>
                                    <?php endforeach; ?>
                                    </ul>
                                <?php       break;
                                case 'dropdown': ?>
                                    <div class="field no-label">
                                        <select class="field"
                                                name="group[<?php echo $block->escapeHtml($i['interest']['id']) ?>]"
                                                id="<?php echo 'mailchimp_group_'.$block->escapeHtml($i['interest']['id']) ?>"
                                                title="<?php echo $block->escapeHtml($i['interest']['title']) ?>">
                                            <option value=""></option>
                                            <?php foreach($i['category'] as $c): ?>
                                                <option value="<?php echo $block->escapeHtml($c['id'])?>" <?php if($c['checked']) { echo 'selected'; } ?>><?php echo $block->escapeHtml($c['name']) ?></option>
                                            <?php endforeach; ?>
                                        </select>

                                    </div>
                                <?php       break;
                                case 'radio': ?>
                                    <ul class="field">
                                        <?php foreach($i['category'] as $c): ?>
                                            <li class="field no-label" style="list-style: none">
                                                <input class=""
                                                       name="group[<?php echo $block->escapeHtml($i['interest']['id']) ?>]"
                                                       type="radio"
                                                       value="<?php echo $block->escapeHtml($c['id']) ?>"
                                                       id="<?php echo 'mailchimp_group_'.$block->escapeHtml($c['id']) ?>"
                                                       title="<?php echo $block->escapeHtml($c['name']) ?>"
                                                    <?php if($c['checked']) { echo 'checked';} ?>
                                                />
                                                <label class="field label"><?php echo $block->escapeHtml($c['name'])?></label>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php       break; ?>
                            <?php endswitch; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action primary"
                    title="<?php echo $block->escapeHtml(__('Subscribe to more detailed newsletters')) ?>">
                <span><?php echo $block->escapeHtml(__('Subscribe to more detailed newsletters')) ?></span>
            </button>
        </div>
    </div>
</form>
<?php echo $block->escapeHtml($block->getMessageAfter()) ?>

</p>
