<?php
/**
 * @var $block \Ebizmarts\MailChimp\Block\checkout\Success
 */
$interest = $block->getInterest();
//echo $interest;
?>
<p>
    <?= $block->escapeHtml($block->getMessageBefore()) ?>
<form class="form" action="<?= $block->escapeUrl($block->getFormUrl()) ?>" method="get" id="mailchimp-groups">
    <fieldset class="fieldset">
            <?php foreach ($interest as $i): ?>
                <div class="field">
                    <label class="label" for="<?= $block->escapeHtml($i['interest']['id']) ?>">
                        <span><?= $block->escapeHtml($i['interest']['title']) ?></span>
                    </label>
                    <div class="control">
                        <div class="fields">
                            <?php switch ($i['interest']['type']):
                                case 'checkboxes': ?>
                                    <ul class="field" style="list-style: none">
                                    <?php foreach ($i['category'] as $c): ?>
                                        <li class="field no-label">
                                            <input class=""
                                                   name="group[<?=  $block->escapeHtml($i['interest']['id']) ?>][<?= $block->escapeHtml($c['id']) ?>]"
                                                   type="checkbox"
                                                   value="<?= $block->escapeHtml($c['id']) ?>"
                                                   id="<?= $block->escapeHtml('mailchimp_group_'.$c['id']) ?>"
                                                   title="<?= $block->escapeHtml($c['name']) ?>"
                                                   <?php if ($c['checked']) { echo $block->escapeHtml('checked');} ?>
                                            />
                                            <label class="field label"><?= $block->escapeHtml($c['name']) ?></label>
                                        </li>
                                    <?php endforeach; ?>
                                    </ul>
                                <?php       break;
                                case 'dropdown': ?>
                                    <div class="field no-label">
                                        <select class="field"
                                                name="group[<?= $block->escapeHtml($i['interest']['id']) ?>]"
                                                id="<?= $block->escapeHtml('mailchimp_group_'.$i['interest']['id']) ?>"
                                                title="<?= $block->escapeHtml($i['interest']['title']) ?>">
                                            <option value=""></option>
                                            <?php foreach ($i['category'] as $c): ?>
                                                <option value="<?= $block->escapeHtml($c['id'])?>" <?php if ($c['checked']) { echo $block->escapeHtml('selected'); } ?>><?= $block->escapeHtml($c['name']) ?></option>
                                            <?php endforeach; ?>
                                        </select>

                                    </div>
                                <?php       break;
                                case 'radio': ?>
                                    <ul class="field">
                                        <?php foreach ($i['category'] as $c): ?>
                                            <li class="field no-label" style="list-style: none">
                                                <input class=""
                                                       name="group[<?= $block->escapeHtml($i['interest']['id']) ?>]"
                                                       type="radio"
                                                       value="<?= $block->escapeHtml($c['id']) ?>"
                                                       id="<?= $block->escapeHtml('mailchimp_group_'.$c['id']) ?>"
                                                       title="<?= $block->escapeHtml($c['name']) ?>"
                                                    <?php if ($c['checked']) { echo $block->escapeHtml('checked');} ?>
                                                />
                                                <label class="field label"><?= $block->escapeHtml($c['name'])?></label>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php       break; ?>
                            <?php endswitch; ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action primary"
                    title="<?= $block->escapeHtml(__('Subscribe to more detailed newsletters')) ?>">
                <span><?= $block->escapeHtml( __('Subscribe to more detailed newsletters')) ?></span>
            </button>
        </div>
    </div>
</form>
<?= $block->escapeHtml($block->getMessageAfter()) ?>

</p>
