<div id="monkey_storeconfirmation" style="display:none;" data-mage-init='{"mailchimpconfirmation":{}}'>
</div>
<div class="actions actions-delete-store">
    <div id="validation_result" class="message-validation hidden"></div>
    <button onclick="mailchimpdeleteconfirmation('<?= $block->escapeHtml($block->getAjaxCheckUrl()) ?>')" class="action-delete-store" type="button" id="<?= $block->escapeHtml($block->getHtmlId()) ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
