<?php
/**
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<div class="actions actions-get-apikey">
    <div id="validation_result" class="message-validation hidden"></div>
    <button onclick="javascript:window.open('<?= $escaper->escapeUrl($block->authorizeRequestUrl()) ?>', 'apiwizard','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=100, top=100, width=500, height=700'); return false;" class="action-get-apikey" type="button" id="<?= $block->getHtmlId() ?>">
        <span><?= $escaper->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
