<div id="monkey_errorconfirmation" style="display:none;" data-mage-init='{"mailchimpconfirmation":{}}'>
</div>
<div class="actions actions-reset-errors">
    <div id="validation_result" class="message-validation hidden"></div>
    <button onclick="mailchimpdeleteconfirmation('<?= $block->escapeUrl($block->getAjaxCheckUrl()) ?>')" class="action-reset-errors" type="button" id="<?= $block->getHtmlId() ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
