<?php
/**
 * Ebizmarts_MailChimp Magento JS component
 *
 * @category    Ebizmarts
 * @package     Ebizmarts_MailChimp
 * @author      Ebizmarts Team <info@ebizmarts.com>
 * @copyright   Ebizmarts (http://ebizmarts.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="configmonkey_apikey" class="admin__page-section-item" style="display:none;"
     data-mage-init='{"configmonkeyapikey":{
     "storeUrl": "<?php echo $this->getUrl('mailchimp/stores/get');?>",
     "detailsUrl": "<?php echo $this->getUrl('mailchimp/ecommerce/getaccountdetails');?>",
     "storeGridUrl": "<?php echo $this->getUrl('mailchimp/stores/index');?>",
     "createWebhookUrl": "<?php echo $this->getUrl('mailchimp/ecommerce/createWebhook');?>",
     "getInterestUrl": "<?php echo $this->getUrl('mailchimp/ecommerce/getInterest');?>"}}'>
</div>
<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">
    <h4>
        <img width="224px" style="padding-left: 15px;" height="60px" src="https://ebizmarts-website.s3.amazonaws.com/Logo_Ebizmarts.png"/><br><br>
        <div style="padding-left: 15px;">
            <p> <strong style="color:#EA7601;"><?php echo $block->escapeHtml(__('MailChimp v')) ?><?php echo $block->escapeHtml($this->getModuleVersion()) ?><?php echo $block->escapeHtml(__(' by')) ?></strong> <a target="_blank" href="http://ebizmarts.com"><strong>ebizmarts</strong></a></p>
            <p><?php echo $block->escapeHtml(__('Need help? See our ')) ?><a href="http://wiki.ebizmarts.com/installation" target="_blank"><?php echo $block->escapeHtml(__('Wiki')) ?></a><?php echo $block->escapeHtml(__(' or browse our ')) ?><a href="http://ebizmarts.com/forums" target="_blank"><?php echo $block->escapeHtml(__('support forums')) ?></a><?php echo $block->escapeHtml(__(' Got feedback? ')) ?><a href="mailto:mailchimp@ebizmarts-desk.zendesk.com?Subject=MailChimp For Magento Version <?php echo $block->escapeHtml($this->getModuleVersion())?>"><?php echo $block->escapeHtml(__('Email us')) ?></a></p>
            <p><?php echo $block->escapeHtml(__('You can find more extension in our ')) ?><a href="http://store.ebizmarts.com" target="_blank"><?php echo $block->escapeHtml(__('Store')) ?></a></p>
        </div>
    </h4>
</div>
